// ThreadPrinter - Content Generators
// Generates different output formats from thread data

// Generate Markdown format
function generateMarkdown(data) {
  const { metadata, tweets, url } = data;
  
  let md = '';
  
  // Header
  md += `# Thread by ${metadata.author.name || metadata.author.handle || 'Unknown'}\n\n`;
  md += `**Source:** ${url}\n`;
  md += `**Extracted:** ${new Date().toLocaleString()}\n\n`;
  md += `---\n\n`;
  
  // Tweets
  tweets.forEach((tweet, index) => {
    md += `## Tweet ${index + 1}\n\n`;
    
    // Author info for replies
    if (tweet.isReply && tweet.author.handle !== metadata.author.handle) {
      md += `*Reply by ${tweet.author.name} (${tweet.author.handle})*\n\n`;
    }
    
    // Content
    const text = tweet.textPlain.replace(/\n/g, '  \n');
    md += `${text}\n\n`;
    
    // Images
    if (tweet.images && tweet.images.length > 0) {
      tweet.images.forEach(img => {
        md += `![${img.alt || 'Image'}](${img.url})\n\n`;
      });
    }
    
    // Videos
    if (tweet.videos && tweet.videos.length > 0) {
      tweet.videos.forEach(video => {
        md += `[Video](${video.url})\n\n`;
      });
    }
    
    // Metadata
    if (tweet.timestamp) {
      md += `*${new Date(tweet.timestamp).toLocaleString()}*\n\n`;
    }
    
    md += `---\n\n`;
  });
  
  // Footer
  md += `\n*Generated by [ThreadPrinter](https://github.com/yourusername/threadprinter)*`;
  
  return md;
}

// Generate HTML format
function generateHTML(data) {
  const { metadata, tweets, url } = data;
  
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(metadata.title || 'Thread')}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      max-width: 700px;
      margin: 0 auto;
      padding: 40px 20px;
      line-height: 1.6;
      color: #0f1419;
      background: #fff;
    }
    .thread-header {
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 2px solid #e1e8ed;
    }
    .thread-title {
      font-size: 24px;
      font-weight: 800;
      margin-bottom: 10px;
    }
    .thread-meta {
      color: #536471;
      font-size: 14px;
    }
    .tweet {
      margin-bottom: 30px;
      padding-bottom: 20px;
      border-bottom: 1px solid #e1e8ed;
    }
    .tweet-header {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 10px;
    }
    .tweet-avatar {
      width: 40px;
      height: 40px;
      border-radius: 50%;
    }
    .tweet-author {
      font-weight: 700;
    }
    .tweet-handle {
      color: #536471;
      font-size: 14px;
    }
    .tweet-time {
      color: #536471;
      font-size: 14px;
    }
    .tweet-text {
      margin: 10px 0;
      white-space: pre-wrap;
    }
    .tweet-text a {
      color: #1d9bf0;
      text-decoration: none;
    }
    .tweet-media {
      margin: 10px 0;
    }
    .tweet-media img {
      max-width: 100%;
      border-radius: 12px;
    }
    .tweet-stats {
      color: #536471;
      font-size: 14px;
      margin-top: 10px;
    }
    .thread-footer {
      margin-top: 40px;
      padding-top: 20px;
      border-top: 1px solid #e1e8ed;
      color: #536471;
      font-size: 13px;
      text-align: center;
    }
  </style>
</head>
<body>
  ${generateStyledHTML(data)}
</body>
</html>`;
}

// Generate styled HTML for preview/PDF
function generateStyledHTML(data, forPrint = false) {
  const { metadata, tweets, url } = data;
  
  let html = '';
  
  // Header
  html += `<div class="thread-header">`;
  html += `<h1 class="thread-title">${escapeHtml(metadata.title || 'Thread')}</h1>`;
  
  // Author info
  if (metadata.author) {
    html += `<div class="author-info">`;
    if (metadata.author.avatar) {
      html += `<img src="${metadata.author.avatar}" alt="" class="author-avatar">`;
    }
    html += `<div class="author-details">`;
    html += `<div class="author-name">${escapeHtml(metadata.author.name || 'Unknown')}</div>`;
    if (metadata.author.handle) {
      html += `<div class="author-handle">${escapeHtml(metadata.author.handle)}</div>`;
    }
    html += `</div>`; // author-details
    html += `</div>`; // author-info
  }
  
  html += `<div class="thread-meta">`;
  html += `<div>Source: <a href="${url}" target="_blank">${url}</a></div>`;
  html += `<div>Extracted: ${new Date().toLocaleString()}</div>`;
  html += `</div>`; // thread-meta
  html += `</div>`; // thread-header
  
  // Tweets
  html += `<div class="thread-tweets">`;
  
  tweets.forEach((tweet, index) => {
    html += `<div class="tweet" data-index="${index}">`;
    
    // Avatar
    if (tweet.author?.avatar) {
      html += `<img src="${tweet.author.avatar}" alt="" class="tweet-avatar">`;
    } else {
      html += `<div class="tweet-avatar" style="background: #e1e8ed;"></div>`;
    }
    
    html += `<div class="tweet-content">`;
    
    // Header
    html += `<div class="tweet-header">`;
    html += `<span class="tweet-author-name">${escapeHtml(tweet.author?.name || 'Unknown')}</span>`;
    if (tweet.author?.handle) {
      html += `<span class="tweet-author-handle">${escapeHtml(tweet.author.handle)}</span>`;
    }
    if (tweet.displayTime) {
      html += `<span class="tweet-time">· ${escapeHtml(tweet.displayTime)}</span>`;
    }
    html += `</div>`; // tweet-header
    
    // Text content
    if (tweet.text) {
      html += `<div class="tweet-text">${tweet.text}</div>`;
    } else if (tweet.textPlain) {
      html += `<div class="tweet-text">${escapeHtml(tweet.textPlain).replace(/\n/g, '<br>')}</div>`;
    }
    
    // Media
    if (tweet.images && tweet.images.length > 0) {
      const gridClass = tweet.images.length === 1 ? 'single-image' : 
                        tweet.images.length === 2 ? 'two-images' :
                        tweet.images.length === 3 ? 'three-images' : 'four-images';
      
      html += `<div class="tweet-media ${gridClass}">`;
      tweet.images.forEach(img => {
        html += `<img src="${img.url}" alt="${escapeHtml(img.alt || '')}" loading="lazy">`;
      });
      html += `</div>`;
    }
    
    // Videos
    if (tweet.videos && tweet.videos.length > 0) {
      tweet.videos.forEach(video => {
        html += `<div class="tweet-video">`;
        html += `<a href="${video.url}" target="_blank">🎥 View Video</a>`;
        html += `</div>`;
      });
    }
    
    // Stats
    if (tweet.stats) {
      html += `<div class="tweet-stats">`;
      if (tweet.stats.replies > 0) {
        html += `<span class="tweet-stat">💬 ${formatNumber(tweet.stats.replies)}</span>`;
      }
      if (tweet.stats.reposts > 0) {
        html += `<span class="tweet-stat">🔄 ${formatNumber(tweet.stats.reposts)}</span>`;
      }
      if (tweet.stats.likes > 0) {
        html += `<span class="tweet-stat">❤️ ${formatNumber(tweet.stats.likes)}</span>`;
      }
      html += `</div>`;
    }
    
    html += `</div>`; // tweet-content
    html += `</div>`; // tweet
  });
  
  html += `</div>`; // thread-tweets
  
  // Footer
  html += `<div class="thread-footer">`;
  html += `Generated by ThreadPrinter · ${tweets.length} tweets extracted`;
  html += `</div>`;
  
  return html;
}

// Utility: Escape HTML
function escapeHtml(text) {
  if (!text) return '';
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

// Utility: Format number
function formatNumber(num) {
  if (num >= 1000000) {
    return (num / 1000000).toFixed(1) + 'M';
  }
  if (num >= 1000) {
    return (num / 1000).toFixed(1) + 'K';
  }
  return num.toString();
}

// Export for module usage
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    generateMarkdown,
    generateHTML,
    generateStyledHTML,
    escapeHtml,
    formatNumber
  };
}
